name: ferum_customs
description: >
  Анализ и сопровождение Python-проекта с FastAPI, Telegram FSM и модульными тестами.

image: universal

workspace:
  root: /ferum_customs-main

setup:
  script: ./setup.sh
  shell: bash
  allowNetwork: true

tasks:
  - .codex/task.md
