name: ferum_customs
description: >
  Внутренний проект для управления сервисными заявками, FSM-ботом и API.
  Цель задачи — устранить выявленные недостатки: улучшить структуру тестов, стилистику кода и подготовить CI.

image: universal

workspace:
  root: /ferum_customs_codex_task_ready

setup:
  script: ./setup.sh
  shell: bash
  allowNetwork: true

tasks:
  - .codex/task.md
