# .pre-commit-config.yaml

default_stages: [commit]
exclude: ^(env|testvenv|\.venv)/
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: "erpnext.*"
        exclude: ".*json$|.*txt$|.*csv|.*md|^\\.venv_dev/"
      - id: check-yaml
        exclude: '^(?:\.venv_dev/|\.codex/tasks/)'
      - id: no-commit-to-branch
        args: ['--branch', 'develop']
        exclude: '^\\.venv_dev/'
      - id: check-merge-conflict
        exclude: '^\\.venv_dev/'
      - id: check-ast
        exclude: '^\\.venv_dev/'
      - id: check-json
        exclude: '^\\.venv_dev/'
      - id: check-toml
        exclude: '^\\.venv_dev/'
      - id: debug-statements
        exclude: '^\\.venv_dev/'

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: f12edd9c7be1c20cfa42420fd0e6df71e42b51ea  # frozen: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [javascript, vue, scss]
        exclude: |
          (?x)^(
            erpnext/public/dist/.*|
            cypress/.*|
            .*node_modules.*|
            .*venv_dev.*|
            .*boilerplate.*|
            erpnext/public/js/controllers/.*|
            erpnext/templates/pages/order.js|
            erpnext/templates/includes/.*
          )$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: a01f0f4088faf34088a795a1fb66aefc5cf099e9  # frozen: v9.32.0
    hooks:
      - id: eslint
        types_or: [javascript]
        args: ['--quiet']
        exclude: |
          (?x)^(
            erpnext/public/dist/.*|
            cypress/.*|
            .*node_modules.*|
            .*venv_dev.*|
            .*boilerplate.*|
            erpnext/public/js/controllers/.*|
            erpnext/templates/pages/order.js|
            erpnext/templates/includes/.*
          )$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 73b0f6d59bbfcb75e17a4653d581c9dfaca13969  # frozen: v0.12.5
    hooks:
      - id: ruff
        name: "Run ruff import sorter"
        args: ["--select=I", "--fix"]
        exclude: '^(?:\.venv_dev/|scripts/)'

      - id: ruff
        name: "Run ruff linter"
        exclude: '^(?:\.venv_dev/|scripts/)'

  - repo: https://github.com/PyCQA/isort
    rev: c8ab4a5b21bac924d106e3103dd7c979fdd0f9bc  # frozen: 6.0.1
    hooks:
      - id: isort
        name: isort (python import sorter)
        args: ["--profile", "black"]
        exclude: '^\.venv_dev/'

  - repo: https://github.com/psf/black
    rev: 8a737e727ac5ab2f1d4cf5876720ed276dc8dc4b  # frozen: 25.1.0
    hooks:
      - id: black
        language_version: python3
        exclude: '^\.venv_dev/'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 850d8bf806620ef89a99381c5cf5ea2c1ea826dd  # frozen: v1.17.0
    hooks:
      - id: mypy
        args:
          - --config-file=mypy.ini
          - --explicit-package-bases
          - ferum_customs/ferum_customs
        additional_dependencies:
          - pydantic-settings
        exclude: '^\.venv_dev/'

  - repo: local
    hooks:
        - id: check-fixtures-doctype
          name: Check fixture JSON doctype field
          entry: scripts/check_fixtures_doctype.py
          language: python
          language_version: python3
          files: ^ferum_customs/fixtures/.*\.json$

  # Consider adding hooks for testing and security checks

ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false
