services:
  mariadb:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 2s
      retries: 10

  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 10

  frappe:
    image: frappe/erpnext:${ERPNEXT_TAG}
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      FRAPPE_PATHS_APPEND: ""
      SITE_NAME: ${FRAPPE_SITE_NAME}
      DB_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      INSTALL_APPS: "erpnext,ferum_customs"
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites
      - .:/home/frappe/frappe-bench/apps/ferum_customs
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /home/frappe/frappe-bench
    entrypoint: /entrypoint.sh
