version: "3.9"

services:
  app:
    command: sleep infinity
    depends_on:
      - mariadb
      - redis
    volumes:
      - frappe-sites:/home/frappe/frappe-bench/sites
      - frappe-apps:/home/frappe/frappe-bench/apps

  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123

  redis:
    image: redis:6.2

volumes:
  frappe-sites:
  frappe-apps:
