
services:
  db:
    image: mariadb:${MARIADB_TAG:-10.6}
    dns: [1.1.1.1, 9.9.9.9]
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${DB_ROOT_HOST:-%}
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:latest
    dns: [1.1.1.1, 9.9.9.9]
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING"]
      interval: 5s
      timeout: 3s
      retries: 20

  frappe:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BENCH_TAG: ${BENCH_TAG:-v5.25.9}
        FRAPPE_BRANCH: ${FRAPPE_BRANCH:-version-15}
        ERPNEXT_BRANCH: ${ERPNEXT_BRANCH:-version-15}
    dns: [1.1.1.1, 9.9.9.9]
    environment:
      SITE_NAME: ${SITE_NAME}
      DB_HOST: db
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_CACHE: ${REDIS_CACHE:-redis://:{$REDIS_PASSWORD}@redis:6379/0}
      REDIS_QUEUE: ${REDIS_QUEUE:-redis://:{$REDIS_PASSWORD}@redis:6379/1}
      REDIS_SOCKETIO: ${REDIS_SOCKETIO:-redis://:{$REDIS_PASSWORD}@redis:6379/2}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - ./ferum_customs:/home/frappe/frappe-bench/apps/ferum_customs
      - ./docker/entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
    command: ["/usr/local/bin/docker-entrypoint.sh", "bench", "start"]

volumes:
  sites:
  db-data:
  redis-data:
