
services:
  web:
    image: frappe/erpnext:${ERPNEXT_TAG:-v15.25.0}
    env_file:
      - .env
    container_name: frappe-web
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis
    command: >
      bash -c "
      cd /home/frappe/frappe-bench &&
      bench start --no-redis --no-watch --web-port 8000"
    ports:
      - "8000:8000"
    volumes:
      - frappe-sites:/home/frappe/frappe-bench/sites
      - frappe-apps:/home/frappe/frappe-bench/apps

  worker:
    image: frappe/erpnext:${ERPNEXT_TAG:-v15.25.0}
    env_file:
      - .env
    container_name: frappe-worker
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis
    command: >
      bash -c "
      cd /home/frappe/frappe-bench &&
      bench worker"
    volumes:
      - frappe-sites:/home/frappe/frappe-bench/sites
      - frappe-apps:/home/frappe/frappe-bench/apps

  schedule:
    image: frappe/erpnext:${ERPNEXT_TAG:-v15.25.0}
    env_file:
      - .env
    container_name: frappe-schedule
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis
    command: >
      bash -c "
      cd /home/frappe/frappe-bench &&
      bench schedule"
    volumes:
      - frappe-sites:/home/frappe/frappe-bench/sites
      - frappe-apps:/home/frappe/frappe-bench/apps

  socketio:
    image: frappe/erpnext:${ERPNEXT_TAG:-v15.25.0}
    env_file:
      - .env
    container_name: frappe-socketio
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis
    command: >
      bash -c "
      cd /home/frappe/frappe-bench &&
      bench socketio"
    ports:
      - "9000:9000"
    volumes:
      - frappe-sites:/home/frappe/frappe-bench/sites
      - frappe-apps:/home/frappe/frappe-bench/apps

