services:
  frappe:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BENCH_TAG: ${BENCH_TAG}
    environment:
      SITE_NAME: ${SITE_NAME}
      DB_HOST: db
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_CACHE: "redis://redis:6379"
      REDIS_QUEUE: "redis://redis:6379"
      REDIS_SOCKETIO: "redis://redis:6379"
      ADMIN_PASSWORD: ${ADMIN_PASSWORD} # Добавлено
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # Добавлено
      FRAPPE_ADMIN_PASSWORD: ${FRAPPE_ADMIN_PASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - ./ferum_customs:/home/frappe/frappe-bench/apps/ferum_customs # Добавлено из override
      - ./docker/entrypoint.sh:/usr/local/bin/docker-entrypoint.sh # Монтирование нового entrypoint
    depends_on:
      - db
      - redis
    command: ["/usr/local/bin/docker-entrypoint.sh", "bench", "start"] # Команда для entrypoint

  db:
    image: mariadb:${MARIADB_TAG}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis-data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

volumes:
  sites:
  db-data:
  redis-data:
