version: '3.9'
services:
  mariadb:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
  redis-cache:
    image: redis:alpine
    ports:
      - "13000:6379"
  redis-queue:
    image: redis:alpine
    ports:
      - "11000:6379"
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
