version: "3.9"

services:
  app:
    command: sleep infinity
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    volumes:
      - frappe-sites:/home/frappe/frappe-bench/sites
      - frappe-apps:/home/frappe/frappe-bench/apps

  mariadb:
    image: mariadb:${MARIADB_TAG:-10.6}
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-uroot", "-p${DB_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 2s
      retries: 10

  redis:
    image: redis:${REDIS_TAG:-6.2}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 10

volumes:
  frappe-sites:
  frappe-apps:
