version: "3.9"

services:
  frappe:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BENCH_TAG: ${BENCH_TAG}
    environment:
      SITE_NAME: test.localhost
      DB_HOST: db
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - ./ferum_customs:/home/frappe/frappe-bench/apps/ferum_customs
    depends_on:
      - db
      - redis-cache
      - redis-queue
    command: >
      bash -c "bench new-site --force test.localhost --db-root-password ${DB_ROOT_PASSWORD} --admin-password ${ADMIN_PASSWORD} && \
               bench --site test.localhost install-app erpnext && \
               bench --site test.localhost install-app ferum_customs && \
               pytest -q"

  db:
    image: mariadb:${MARIADB_TAG}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

  redis-cache:
    image: redis:${REDIS_TAG}

  redis-queue:
    image: redis:${REDIS_TAG}

volumes:
  sites:
  db-data:
