version: "3.9"

services:
  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot"]
      interval: 10s
      retries: 5

  redis:
    image: redis:6
    volumes:
      - redisdata:/data

  frappe:
    build:
      context: .
      dockerfile: Dockerfile.frappe
      args:
        - PYTHON_VERSION=3.11
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    environment:
      SITE_NAME: ${SITE_NAME:-test_site}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}
      DB_ROOT_PASSWORD: root
    volumes:
      - ./sites:/workspace/sites
    command: >
      bash -c "
        bench new-site $SITE_NAME
          --admin-password $ADMIN_PASSWORD
          --mariadb-root-password $DB_ROOT_PASSWORD
          --no-mariadb-socket &&
        bench --site $SITE_NAME install-app erpnext &&
        bench --site $SITE_NAME install-app ferum_customs &&
        bench start
      "

volumes:
  dbdata:
  redisdata:
