name: Fix missing Frappe site DB and admin access
description: |
  Проверяет наличие базы данных, пользователя, доступов, 
  и устанавливает пароль администратора Frappe-сайта.
language: bash

inputs:
  SITE:
    description: Название сайта (папка в sites/)
    default: erp.ferumrus.ru
  ADMIN_PASSWORD:
    description: Новый пароль администратора
    default: fFeRu1011#f

steps:
  - name: Проверка и загрузка DB_NAME и DB_PASSWORD
    run: |
      SITE_CONFIG="sites/${SITE}/site_config.json"
      if [ ! -f "$SITE_CONFIG" ]; then
        echo "❌ site_config.json не найден: $SITE_CONFIG" >&2
        exit 1
      fi

      export DB_NAME=$(jq -r '.db_name' "$SITE_CONFIG")
      export DB_PASSWORD=$(jq -r '.db_password' "$SITE_CONFIG")

      if [[ -z "$DB_NAME" || "$DB_NAME" == "null" ]]; then
        echo "❌ db_name не найден в site_config.json" >&2
        exit 1
      fi

      echo "✅ Загружено имя БД: $DB_NAME"
      echo "::set-env name=DB_NAME::$DB_NAME"
      echo "::set-env name=DB_PASSWORD::$DB_PASSWORD"

  - name: Создание базы данных и пользователя (если не существует)
    run: |
      docker compose -f frappe_docker/pwd.yml exec -T db         mariadb -uroot -p"$MYSQL_ROOT_PASSWORD" <<EOF
      CREATE DATABASE IF NOT EXISTS \`$DB_NAME\`;
      CREATE USER IF NOT EXISTS '$DB_NAME'@'%' IDENTIFIED BY '$DB_PASSWORD';
      GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_NAME'@'%';
      FLUSH PRIVILEGES;
EOF

  - name: Проверка подключения к БД от имени Frappe
    run: |
      docker compose -f frappe_docker/pwd.yml exec backend         bash -c "mysql -h db -u$DB_NAME -p$DB_PASSWORD -e 'SHOW TABLES IN \`$DB_NAME\`;' || exit 1"

  - name: Установка пароля администратора Frappe
    run: |
      docker compose -f frappe_docker/pwd.yml exec backend         bash -c "bench --site $SITE set-admin-password $ADMIN_PASSWORD"
