FROM python:3.11-slim

WORKDIR /app
COPY ../src /app

RUN pip install --no-cache-dir \
    fastapi==0.110.0 \
    uvicorn[standard]==0.29.0 \
    aiogram==3.3.0 \
    requests==2.31.0 \
    oauthlib==3.2.2 \
    python-dotenv==1.0.1

CMD ["sh", "-c", "uvicorn main:app --host ${FASTAPI_HOST:-0.0.0.0} --port ${FASTAPI_PORT:-8000}"]
