name: Integration

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ secrets.PYTHON_VERSION }}  # Use a variable for flexibility
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install ".[dev,test]"  # Be explicit about dependencies
      - name: Start stack
        run: docker compose up -d --build  # Ensure Dockerfile is secure
      - name: Verify pytest-cov plugin
        run: pytest --help | grep -- '--cov'

      - name: Run integration tests
        run: pytest --cov=ferum_customs --cov-report=term-missing -q tests/integration

      - name: Clean up
        if: always()  # Ensure cleanup runs even if tests fail
        run: docker compose down
